name: Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Validate composer.json and composer.lock
      run: cd docs && composer validate

    - name: Composer
      run: cd docs && composer install --no-progress --no-suggest

    - name: Node
      run: cd docs && npm install

    - name: Production
      run: cd docs && npm run prod

    - name: CNAME
      run: cd docs && echo "laraxot.github.io/module_xot_fila3" > ./build_production/CNAME

    - name: gh-pages
<<<<<<< HEAD
      uses: JamesIves/github-pages-deploy-action@latest
=======
      uses: JamesIves/github-pages-deploy-action@v4.6.3
>>>>>>> 80b704a (Bump JamesIves/github-pages-deploy-action from 4.6.1 to 4.6.3)
      with:
        branch: gh-pages
        folder: ./docs/build_production
